version: "3.8"
services:
  app:
    image: vladokuskov/prod-minddaily-frontend:latest
    build:
      context: .
      target: production
    environment:
      - NODE_ENV=production
    ports:
      - "8085:8085"