name: Deploy stage-minddaily-frontend

on:
  push:
    branches: [ "development" ]

jobs:
  build:
    name: Build and publish image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build -f docker/staging/Dockerfile . --tag ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_STAGE_IMAGE_NAME }}:latest

    - name: Publish Docker image
      run: |
        docker login -u vladokuskov -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker push ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_STAGE_IMAGE_NAME }}

  deploy:
    needs: build
    name: Deploy image
    runs-on: ubuntu-latest

    steps:
      - name: Create ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSHKEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} > ~/.ssh/known_hosts

      - name: Pull and run container
        run: ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "cd ${{ secrets.WORK_DIR_STAGE }} && docker image prune -f && docker compose pull && docker compose up -d && exit"
      - name: Cleanup
        run: rm -rf ~/.ssh